# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "mysql2-cs-bind"
gem "rack-flash3"
#gem "unicorn"
gem "rhebok"
gem "foreman"
gem "stackprof"
gem "erubis"
gem "rack-lineprof"
gem "redis"
gem "hiredis"
